# Generated by Django 3.1.2 on 2020-11-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='paused',
            field=models.BooleanField(blank=True, default=False, verbose_name='paused'),
        ),
        migrations.RemoveField(
            model_name='todo',
            name='complete',
        ),
        migrations.AddField(
            model_name='todo',
            name='complete',
            field=models.BooleanField(blank=True, default=False, verbose_name='complete'),
        ),
    ]
